---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      automountServiceAccountToken: false
      containers:
        - name: spring-boot-app
          image: spring-boot-postgres:0.0.1
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
              ephemeral-storage: "256Mi"
            limits:
              memory: "512Mi"
              ephemeral-storage: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-app
  namespace: default
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: spring-boot-app
  type: ClusterIP
---